version: 2.1

orbs:
  node: circleci/node@1.1.6

defaults: &defaults
  executor:
      name: node/default

only-release: &only-release
  filters:
    # Ignore all branches
    branches:
      ignore: /.*/
    # And only run on version tags
    tags:
      only: /^v(\d+)\.(\d+)\.(\d+).*/

only-non-release: &only-non-release
  filters:
    tags:
      ignore: /^v(\d+)\.(\d+)\.(\d+).*/

jobs:
  smoke-test:
    <<: *defaults
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: 
                name: Install dependencies
                command: yarn
            - run: 
                name: Build
                command: yarn build
            - run: 
                name: Test
                command: yarn test:version -v 3.1.1

  test:
    <<: *defaults
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: 
                name: Install dependencies
                command: yarn
            - run: 
                name: Build
                command: yarn build
            - run: 
                name: Test
                command: yarn test

  deploy:
    <<: *defaults
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: 
                name: Build
                command: yarn build
            - run:
                name: Authenticate for NPM
                command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/dist/.npmrc
            - run:
                name: Publish package
                command: yarn release

workflows:
  test-and-deploy:
    jobs:
      - smoke-test:
          <<: *only-non-release

      - test:
          <<: *only-release

      - deploy:
          <<: *only-release
          requires: 
            - test
